version: "3"

services:
  alp-t2:
    image: 666pehid666/alp-t2:latest
    ports:
       - 8080:80
    deploy:
        replicas: 5
    environment:
        DEVOPS: test_for_compose

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
       - 8081:8081

  app:
    image: tomcat:9.0
    depends_on:
      - db
    environment:
      CATALINA_BASE:   /usr/local/tomcat
      CATALINA_HOME:   /usr/local/tomcat
      CATALINA_TMPDIR: /usr/local/tomcat/temp
