version: "3.9"

services:
  alp-t2:
    image: 666pehid666/alp-t2:latest
    ports: 8080:80
    deploy:
        replicas: 5
    environment:
        DEVOPS: test_for_compose
  db:
    image: mongo-mongo-express
    restart: always
    ports: 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
  app:
     image: jetbrains/teamcity-agent
     depends_on: db
     environment:
        SERVER_URL: test.com
        AGENT_NAME: Smith