---
#Playbook for ELK STACK, one-column syntaxis
- hosts: db

  tasks:

    - name: Add an Apt signing key
      become: yes
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: set apt list
      become: yes
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list

    - name: install Elastik
      become: yes
      apt:
        update_cache: yes
        pkg:
         - apt-transport-https
         - elasticsearch

    - name: Elastic config
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'network.host'
        line: 'network.host: 0.0.0.0'

    - name: Updating Elastic Config (Port Number)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'http.port'
        line: 'http.port: 9200'

    - name: Updating Elastic Config (Node Name)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: node-1'

    - name: Updating Elastic Config (Cluster Initial Master Nodes)
      become: yes
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        line: 'cluster.initial_master_nodes: ["node-1"]'

    - name: start elasticsearch
      become: yes
      service:
        name: elasticsearch
        state: started
        enabled: yes

#Kibana
    - name: Install Kibana
      become: yes
      apt:
        name: kibana

    - name: Update Kibana Config (IP Address)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.host'
        line: 'server.host: "192.168.100.26"'

    - name: Update Kibana Config (Kibana URL)
      become: yes
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://localhost:9200"]'

    - name: Start Kibana Service
      become: yes
      service:
        name: kibana
        state: started
        enabled: yes

#Logstash
    - name: install logstash
      become: yes
      apt:
        name: logstash
        state: present

#Nginx
- hosts: web

  vars_files:
    - pb_elk_vars.yml
  vars:
    kibana_cfg: ./kibana
    kibana_dest: /etc/nginx/sites-available/kibana

  tasks:

  - name: install nginx
    become: yes
    apt:
       name: nginx
       state: present

  - name: create pass auth
    become: yes
    shell: echo "admin:$(openssl passwd -apr1 {{ pass }})" > /etc/nginx/htpasswd.kibana

  - name: rm default site
    become: yes
    file:
      dest: /etc/nginx/sites-enabled/default
      state: absent

  - name: copy site cfg
    become: yes
    copy:
      src: "{{ kibana_cfg }}"
      dest: "{{ kibana_dest }}"
      mode: '0555'
    notify: restart_nginx

  - name: ln site enable
    become: yes
    file:
      src: /etc/nginx/sites-available/kibana
      dest: /etc/nginx/sites-enabled/kibana
      state: link

  - name: start nginx service
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes


  handlers:
  - name: restart_nginx
    become: yes
    service:
      name: nginx
      state: restarted
